name: Build Workflow
on:
   workflow_dispatch:
      inputs:
         build_type:
            description: 'Build Configuration to use (Debug, Release, RelWithDebInfo or MinSizeRel).'
            required: false
            default: 'Debug'

   push:
      branches:
      - master
      paths-ignore:
      - '**.md'
      - '**/doc'

   pull_request:
      types:
      - opened
      - synchronize
      - reopened
      paths-ignore:
      - '**.md'
      - '**/doc'

jobs:
   Windows-x64:
      name: Windows x64
      runs-on: windows-2019

      defaults:
         run:
            shell: msys2 {0}

      steps:
      -  name: Install MSYS2
         uses: msys2/setup-msys2@v2
         with:
            msystem: MINGW64

      -  name: Set build configuration
         id: build_configuration
         run: |
            BUILD_TYPE=${{github.event.inputs.build_type}}
            echo "build_type=${BUILD_TYPE:-"Debug"}" >> $GITHUB_OUTPUT

      -  name: Setup Dependencies
         run: |
            pacman -S --noconfirm git mingw-w64-x86_64-toolchain p7zip mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-nsis mingw-w64-x86_64-gettext make mingw-w64-x86_64-SDL2

      -  name: Checkout
         uses: actions/checkout@v4

      -  name: Build
         run: |-
            mkdir ${{steps.build_configuration.outputs.build_type}}
            cd ${{steps.build_configuration.outputs.build_type}}
            cmake -G "MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-mingw-w64-x86_64.cmake -DCMAKE_BUILD_TYPE=${{steps.build_configuration.outputs.build_type}} -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="c:/Program Files/M.A.X. Port" ..
            cmake --build . --parallel

      -  name: Test
         run: |
            cd ${{steps.build_configuration.outputs.build_type}}
            ctest

      -  name: Package
         run: |
            cd ${{steps.build_configuration.outputs.build_type}}
            cpack --config CPackConfig.cmake
            cpack --config CPackSourceConfig.cmake
            mkdir -p Artifacts/Windows-x64
            cp *-win64.exe Artifacts/Windows-x64/
            cp *-win64.7z Artifacts/Windows-x64/
            cp *-Source.7z Artifacts/Windows-x64/
            7z a -mx9 -bd max-port-win64-symbols.7z max.debug
            cp max-port-win64-symbols.7z Artifacts/Windows-x64/

      -  name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
            name: ${{github.job}}
            path: ${{steps.build_configuration.outputs.build_type}}/Artifacts